- APIMatic.Core.Test/Utilities/TestHelperTest.cs
- APIMatic.Core/Utilities/CoreHelper.cs
- APIMatic.Core/Utilities/TestHelper.cs
- README.md
Refactored CoreHelper and TestHelper to decrease cognitive complexity.
> refactor(decrease-complexity): refactor to decrease complexity 

- APIMatic.Core.Test/Utilities/CoreHelperTest.cs
- APIMatic.Core/Utilities/CoreHelper.cs
Added the support for map of complex type 
closes #22
> feat(map-of-complextypes): add the support for map of complex type in query parameters

- APIMatic.Core/APIMatic.Core.csproj
The following PR removes the generatePackageOnBuild tag from the csproj file. Removing this tag allows the don't pack command to run successfully on the core-lib project.
Closes #30
> build(csproj): remove generatePackageOnBuild tag from csproj

- APIMatic.Core.Test/Api/HttpPost/ApiCallPostTest.cs
- APIMatic.Core/Request/Parameters/HeaderParam.cs
The following PR fixes the NullReferenceException being thrown by the RequestBuilder with null header values from the API call. A null check has been added to make the Header value null which is handled gracefully in the HttpClientWrapper.
Closes #41
> fix(request-builder): add null check in HeaderParam.Apply

- APIMatic.Core.Test/APIMatic.Core.Test.csproj
- APIMatic.Core/APIMatic.Core.csproj
- APIMatic.Core/Types/VoidType.cs
- APIMatic.Core/Utilities/TestHelper.cs
- APIMatic.Core/Utilities/XmlUtility.cs
The following PR updates the referred external packages in the core-lib and core-lib test projects to make sure that the C# core-lib is up-to-date and has the latest fixes and improvements.
Packages updated in **APIMatic.Core**:
- Microsoft.Json.Pointer
- Polly
- SonarAnalyzer.CSharp
- System.Collections.Immutable
Packages updated in **APIMatic.Core.Test**:
- Microsoft.NET.Test.Sdk
- NUnit3TestAdapter
- SonarAnalyzer.CSharp
> build(package): update referred packages to latest version

- .editorconfig
- APIMatic.Core.Test/Http/CoreHttpClientConfigurationTest.cs
- APIMatic.Core.Test/Http/HttpClientWrapperSSLTest.cs
- APIMatic.Core.Test/TestBase.cs
- APIMatic.Core/Http/Configuration/CoreHttpClientConfiguration.cs
- APIMatic.Core/Http/Configuration/ICoreHttpClientConfiguration.cs
- APIMatic.Core/Http/HttpClientWrapper.cs
Adds implementation for skipping SSL cert verification to HttpClientConfiguration and HttpClientWrapper.
Closes #43
> fix(http-client-wrapper): implement skipping SSL cert verification

- APIMatic.Core.Test/Utilities/CoreHelperTest.cs
- APIMatic.Core/Utilities/Converters/NumberEnumConverter.cs
This PR added a fix for the bug where the NumberEnumConverter throws unable to convert exception when trying to convert a valid enum value to a Nullable Enum
We need to cover such edge cases to make the SDKs unbreakable
> fix(number-enum-deserialization): added fixes for nullable enum deserialization with valid values

- APIMatic.Core.Test/Utilities/CoreHelperTest.cs
- APIMatic.Core/Utilities/CoreHelper.cs
This PR fixes a bug where we were serializing the boolean values as `True` and `False` instead of `true` and `false` while sending them in query string
Although the query parameter values are case insensitive, but we need to make sure that the serialization across our tooling remain same
> fix(bool-serialization-query): prefered `true` as the serializable bool value for query

- APIMatic.Core.Test/AuthenticationTest.cs
- APIMatic.Core/Authentication/AuthGroupBuilder.cs
- APIMatic.Core/Types/Sdk/Exceptions/AuthValidationException.cs
This PR fixes a bug for multipleAuth's combination `Auth1 OR Auth2` where both authentications Auth1 and Auth2 are being applied. Instead, we need to apply either Auth1 or Auth2 to the request for such cases.
We needed to fix the OR auth applying functionality
Closes #56 
> fix(or-multiple-auth): applying only the first available auth for OR cases

- APIMatic.Core.Test/Utilities/OneOfContainerTest.cs
- APIMatic.Core/Utilities/Converters/UnionTypeConverter.cs
This PR added support for the null values to pass while deserialization if none of the inner types are matched as the OAF containers are nullable by default
We were required to resolve a critical deserialization issue
Closes #58 
> fix(oneof-anyof-nulls): added fix for deserializing null values to oaf containers

- APIMatic.Core.Test/Utilities/CoreHelperTest.cs
- APIMatic.Core/Utilities/Converters/JsonStringConverter.cs
This PR makes the `JsonStringConverter` class write directly to the `JsonWriter` instead of delegating to the serializer.
Previous delegation of serialization to the serializer resulted in a stack overflow where Newtonsoft.JSON external code called our `WriteJson` and our `WriteJson` called Newtonsoft.JSON external code. The serializer in the arguments of `WriteJson` is a reference to the [calling serializer](https://www.newtonsoft.com/json/help/html/M_Newtonsoft_Json_JsonConverter_WriteJson.htm) which is why it resulted in a stack overflow.
Closes #60 
N/A
N/A
I have tested this by trying the new unit test.
> fix(serialization): stack overflow in JsonStringConverter

- APIMatic.Core.Test/MockTypes/Models/MonthNumber.cs
- APIMatic.Core.Test/MockTypes/Models/WorkingDays.cs
- APIMatic.Core.Test/Utilities/CoreHelperTest.cs
- APIMatic.Core/Utilities/Converters/UnknownEnumConverter.cs
In order to be able to relax enum validation during deserialization, we had two options:
1. We can make the enum property nullable in the SDK so that when we deserialize the response and it doesn't match any existing enum value, it assigns null.
2. We can add a new special enum value (like _Unknown) in the SDK so that when we deserialize the response and it doesn't match any existing enum value, it assigns that special enum value.
Since `nullable` properties already have a set meaning, it wouldn't make sense to cause confusion by giving `null` yet another purpose. The second option allows us to be more explicit about what we mean when we allow any unknown values during deserialization.
Therefore, the second option has been implemented.
- Added new type of `JsonConverter` to gracefully …
> feat(enums): relaxing enum validation at deserialization

- APIMatic.Core.Test/AuthenticationTest.cs
- APIMatic.Core.Test/GlobalConfigurationTest.cs
- APIMatic.Core.Test/Http/HttpClientWrapperSSLTest.cs
- APIMatic.Core.Test/Http/HttpClientWrapperTest.cs
- APIMatic.Core/APIMatic.Core.csproj
- APIMatic.Core/ApiCall.cs
- APIMatic.Core/Authentication/AuthGroupBuilder.cs
- APIMatic.Core/Authentication/AuthManager.cs
- APIMatic.Core/Request/RequestBuilder.cs
Added support for OAuth2 auto refresh in client credentials flow
Added additional changes
> feat: add auto refresh token support

- APIMatic.Core.Test/Api/HttpGet/ApiCallGetTest.cs
- APIMatic.Core.Test/TestBase.cs
- APIMatic.Core.Test/Utilities/CoreHelperTest.cs
- APIMatic.Core/Response/ResponseHandler.cs
- APIMatic.Core/Utilities/CoreHelper.cs
This PR adds complete support for returning nullable response types using the nullability check of the generic `ResponseType` to set the response types as nullable when content is missing.
Previously response handler was throwing an exception when a response with no content is received.
Closes #72 
N/A
N/A
Unit tests were added to test this feature
> feat: adds handling for missing content with unit tests

- APIMatic.Core/Types/HttpCallBack.cs
This PR makes `OnBeforeHttpRequestEventHandler` and `OnAfterHttpResponseEventHandler` methods virtual. This allows SDKs to override these methods and invoke user-overridden callbacks methods provided in the SDK class.
- To make the Callback available for SDK class to override
- To execute the user provided callbacks
Closes #78 
List the steps that were taken to test the …
> refactor(http-callback): make Http Callback class override-able

- .editorconfig
- APIMatic.Core.Test/MockTypes/Models/SimpleModelWithAdditionalPropertiesBaseModel.cs
- APIMatic.Core.Test/MockTypes/Models/SimpleModelWithAdditionalPropertiesField.cs
- APIMatic.Core.Test/Utilities/CoreHelperTest.cs
- APIMatic.Core/Utilities/CoreHelper.cs
This PR addresses an issue with the handling of additional properties in models that use [JsonExtensionData]. Specifically, it ensures that additional properties are flattened along with the model’s main members when data is sent as form data. Previously, the additional properties were being sent as a nested dictionary in form data, causing inconsistencies between the form data and the JSON body representation.
Flattening the additional properties in form data ensures consistency between how data is represented in both the JSON body and form data formats. This alignment is important for APIs that process form data in a similar way to JSON payloads, ensuring the behavior is predictable and that consumers of the API receive a consistent structure. Additionally, this change improves …
> fix(request-form): add handling for additional properties

- APIMatic.Core/APIMatic.Core.csproj
Changed `Newtonsoft.Json` version to a flexible range (13.0.*) to allow patch updates while maintaining compatibility.
Ensures the application benefits from minor bug fixes and updates without requiring manual intervention.
> chore(deps): update Newtonsoft.Json to version range 13.0.*

- APIMatic.Core/APIMatic.Core.csproj
Move Newtonsoft.Json dependency from wildcard to a version range to support Dependabot updates and maintain compatibility.
> chore(deps): update Newtonsoft.Json to use version range

- APIMatic.Core.Test/APIMatic.Core.Test.csproj
- APIMatic.Core.Test/TypesTest.cs
- APIMatic.Core/Types/Sdk/CoreContext.cs
- APIMatic.Core/Types/Sdk/CoreRequest.cs
- APIMatic.Core/Types/Sdk/CoreResponse.cs
- Removed ToString() overrides from HttpContext, HttpRequest, and HttpResponse to prevent exposure of sensitive information.
- Bump package System.Net.Http.Json in test project due to reported vulnerability
ToString() overrides in HTTP-related classes (e.g., HttpContext, HttpRequest, HttpResponse) risk exposing sensitive information.
Closes #97
> fix(http-to-string): remove ToString() overrides

- APIMatic.Core/ApiCall.cs
- APIMatic.Core/Authentication/AuthGroupBuilder.cs
- APIMatic.Core/Http/HttpClientWrapper.cs
- APIMatic.Core/Request/RequestBuilder.cs
- Applied ConfigureAwait(false) to await calls in async methods.
- Ensured proper async handling to prevent UI or request thread blocking.
- Calling async methods from synchronous code without ConfigureAwait(false) can cause deadlocks, especially in UI or ASP.NET applications.
- This fix ensures that awaited tasks do not attempt to resume execution on the original synchronization context, preventing the client from freezing.
The fix was tested using a C# client generated from an ASP.NET Web App targeting .NET Framework 4.8.
> fix(client): prevent client freeze when calling async from sync methods

- .github/workflows/test.yml
- README.md
- sonar-project.properties
- Added SonarQube scan step to the GitHub Actions workflow
- Added SonarQube badges to the README
Replace CodeClimate with SonarQube for test coverage analysis.
> ci: migrate test coverage report to SonarQube
